# Generated by Django 2.2.2 on 2019-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstantElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="Key"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Text"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="",
                        verbose_name="Picture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Picture")),
                ("name", models.CharField(max_length=250, verbose_name="Picture name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OurWeapon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Picture")),
                ("name", models.CharField(max_length=250, verbose_name="Tool name")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="", verbose_name="Avatar")),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="First and last name"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("pl", "Project Leader"),
                            ("lca", "Lead Concept Artist"),
                            ("lgd", "Lead Game Designer"),
                            ("ca", "Concept Artist"),
                            ("3d", "3D Graphic"),
                            ("gp", "Gameplay programmer"),
                            ("p", "Producer"),
                            ("ss", "Social Specialist"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
