# Generated by Django 2.2.2 on 2019-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("LivingstoneWebpage", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SeoMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65, verbose_name="Head title")),
                (
                    "description",
                    models.CharField(max_length=160, verbose_name="Meta description"),
                ),
                (
                    "keywords",
                    models.CharField(
                        max_length=1000, verbose_name="Keywords (comma separated)"
                    ),
                ),
            ],
        )
    ]
