# Generated by Django 2.2.2 on 2019-06-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("LivingstoneWebpage", "0002_seometadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="seometadata",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="Site",
            ),
            preserve_default=False,
        )
    ]
