# Generated by Django 2.2.2 on 2019-06-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("LivingstoneWebpage", "0003_seometadata_site")]

    operations = [
        migrations.AlterField(
            model_name="seometadata",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="Site",
            ),
        )
    ]
