# Generated by Django 2.2.2 on 2019-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("LivingstoneWebpage", "0004_auto_20190608_1304")]

    operations = [
        migrations.RemoveField(model_name="constantelement", name="id"),
        migrations.AddField(
            model_name="galleryimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ourweapon", name="order", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="teammember", name="order", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="constantelement",
            name="key",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Key",
            ),
        ),
        migrations.AlterField(
            model_name="seometadata",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="sites.Site",
                verbose_name="Site",
            ),
        ),
    ]
