# Generated by Django 2.2.2 on 2019-06-11 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivingstoneWebpage', '0005_auto_20190608_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='ourweapon',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='span',
            field=models.IntegerField(default=4, help_text='Digit between 1-12. How much space avatar should take. See bootstrap grid', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Max 250 characters', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='size 900x600 px', upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(help_text='Max 25 characters', max_length=25, verbose_name='Picture name'),
        ),
    ]
