# Generated by Django 2.2.2 on 2019-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion


def populate_position(apps, _):
    TeamMember = apps.get_model("LivingstoneWebpage", "TeamMember")
    PositionName = apps.get_model("LivingstoneWebpage", "PositionName")

    for member in TeamMember.objects.all():
        member.position_name = PositionName.objects.get(
            name=member.get_position_display()
        )
        member.save()


class Migration(migrations.Migration):

    dependencies = [("LivingstoneWebpage", "0010_auto_20190616_1815")]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="position_name",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="LivingstoneWebpage.PositionName",
            ),
        ),
        migrations.RunPython(populate_position),
    ]
