# Generated by Django 2.2.2 on 2019-06-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivingstoneWebpage', '0011_teammember_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
    ]
