# Generated by Django 2.2.3 on 2019-08-01 07:00

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LivingstoneWebpage', '0016_auto_20190621_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=thumbnails.fields.ImageField(help_text='size 900x700 px (square size 300x175px)', upload_to='', verbose_name='Picture'),
        ),
    ]
