# Generated by Django 2.2.4 on 2019-08-30 02:31

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


def copy_constant_element(apps, schema):
    ConstantElement = apps.get_model("LivingstoneWebpage", "ConstantElement")
    TempConstantElement = apps.get_model("LivingstoneWebpage", "TempConstantElement")
    for object in ConstantElement.objects.all():
        TempConstantElement.objects.get_or_create(key=object.key, text=object.text, image=object.image, link=object.link, uuid=object.uuid, site=object.site)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('LivingstoneWebpage', '0021_auto_20190828_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempConstantElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, default=None, help_text='About image: 1900x710px', null=True, upload_to='', verbose_name='Picture')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'unique_together': {('key', 'uuid')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RunPython(copy_constant_element, migrations.RunPython.noop)
    ]
