# Generated by Django 2.2.4 on 2019-08-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivingstoneWebpage', '0022_tempconstantelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstantElement',
        ),
    ]
