# Generated by Django 2.2.4 on 2019-08-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('LivingstoneWebpage', '0023_delete_constantelement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempConstantElement',
            new_name='ConstantElement',
        ),
    ]
