# Generated by Django 2.2.4 on 2019-08-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('LivingstoneWebpage', '0024_auto_20190830_0238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constantelement',
            unique_together={('key', 'uuid', 'site')},
        ),
    ]
