version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
      - media:/media
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      STATIC_ROOT: /static
      MEDIA_ROOT: /media
      SECRET_KEY: "fasdfdf34870fjk34ousadf834lfhad3i743fsda"
    ports:
      - 8000:8000
    depends_on:
      - db
  assets:
    image: nginx
    volumes:
    - static:/usr/share/nginx/html/static
    - media:/usr/share/nginx/html/media
    ports:
    - "8080:80"
volumes:
  postgres_data:
  static:
  media: