export const SET_IMAGES = 'SET_IMAGES';
export const SET_ABOUT_TEXT = 'SET_ABOUT_TEXT';
export const SET_CONTACT_TEXT = 'SET_CONTACT_TEXT';
export const SET_TEAM_MEMBERS = 'SET_TEAM_MEMBERS';
export const SET_WEAPONS = 'SET_WEAPONS';